# Path where the mods should be downloaded
mod_path = "/minecraft/mods"

# Game version for mods
version = "1.19.4"

# Loader
loader = "fabric"

# Examples
mod_ids = [
  "gvQqBUqZ", # Lithium
  "uXXizFIs", # FerriteCore
  "H8CaAYZC", # Starlight
  "fQEb0iXm", # Krypton
]
